{
 "title": "Bsky Statistics",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "rate_interval", "label": "Rate interval", "query": "1m,5m,10m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Posts by language",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "posts/h" } },
   "targets": [
    {
     "expr": "sum by(lang) (rate(indexer_posts_by_language_count[$rate_interval])*60*60)",
     "legendFormat": "{{lang}}"
    }
   ]
  },
  {
   "title": "Total Users",
   "type": "stat",
   "gridPos": { "h": 10, "w": 5, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "repos_seen{job=\"db\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time to 10 milion users",
   "type": "stat",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "10000000/(rate(repos_fully_indexed{job=\"db\"}[$rate_interval])*60*60)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Posts by language (Europe only -en)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "posts/h" } },
   "targets": [
    {
     "expr": "sum by(lang) (rate(indexer_posts_by_language_count{lang=~\"bg|cs|da|el|et|fi|ga|hr|hu|lt|lv|nl|ro|sk|sl|sv|uk|uk-UA|pl|de|it|DE|English|Fr|mt|nl-NL|pt|sv-FI|sv-SE\"}[$rate_interval])) * 60 * 60",
     "legendFormat": "{{lang}}"
    }
   ]
  },
  {
   "title": "Posts by language (-en -ja)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "posts/h" } },
   "targets": [
    {
     "expr": "sum by(lang) (rate(indexer_posts_by_language_count{lang!~\"en|ja\"}[$rate_interval])) * 60 * 60",
     "legendFormat": "{{lang}}"
    }
   ]
  },
  {
   "title": "Language by [old] PDS (uk)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "posts/h" } },
   "targets": [
    {
     "expr": "label_replace(sum by(remote) (rate(indexer_posts_by_language_count{lang=\"uk\", remote=~\"https://amanita.us-east.host.bsky.network|https://enoki.us-east.host.bsky.network|https://inkcap.us-east.host.bsky.network|https://lionsmane.us-east.host.bsky.network|https://morel.us-east.host.bsky.network|https://oyster.us-east.host.bsky.network|https://porcini.us-east.host.bsky.network|https://puffball.us-east.host.bsky.network|https://shiitake.us-east.host.bsky.network\"}[$rate_interval])*60*60), \"remote\", \"$1\", \"remote\", \"https://(.*).us-(west|east).host.bsky.network\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Language by [new] PDS (uk)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "posts/h" } },
   "targets": [
    {
     "expr": "label_replace(sum by(remote) (rate(indexer_posts_by_language_count{lang=\"uk\", remote!~\"https://amanita.us-east.host.bsky.network|https://enoki.us-east.host.bsky.network|https://inkcap.us-east.host.bsky.network|https://lionsmane.us-east.host.bsky.network|https://oyster.us-east.host.bsky.network|https://morel.us-east.host.bsky.network|https://porcini.us-east.host.bsky.network|https://puffball.us-east.host.bsky.network|https://shiitake.us-east.host.bsky.network\"}[$rate_interval])*60*60), \"remote\", \"$1\", \"remote\", \"https://(.*).us-(west|east).host.bsky.network\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Language by [old] PDS (ru)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "posts/h" } },
   "targets": [
    {
     "expr": "label_replace(sum by(remote) (rate(indexer_posts_by_language_count{lang=\"ru\", remote=~\"https://amanita.us-east.host.bsky.network|https://enoki.us-east.host.bsky.network|https://inkcap.us-east.host.bsky.network|https://lionsmane.us-east.host.bsky.network|https://oyster.us-east.host.bsky.network|https://morel.us-east.host.bsky.network|https://porcini.us-east.host.bsky.network|https://puffball.us-east.host.bsky.network|https://shiitake.us-east.host.bsky.network\"}[$rate_interval])*60*60), \"remote\", \"$1\", \"remote\", \"https://(.*).us-(west|east).host.bsky.network\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Language by [new] PDS (ru)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "posts/h" } },
   "targets": [
    {
     "expr": "label_replace(sum by(remote) (rate(indexer_posts_by_language_count{lang=\"ru\", remote!~\"https://amanita.us-east.host.bsky.network|https://enoki.us-east.host.bsky.network|https://inkcap.us-east.host.bsky.network|https://lionsmane.us-east.host.bsky.network|https://morel.us-east.host.bsky.network|https://oyster.us-east.host.bsky.network|https://porcini.us-east.host.bsky.network|https://puffball.us-east.host.bsky.network|https://shiitake.us-east.host.bsky.network\"}[$rate_interval])*60*60), \"remote\", \"$1\", \"remote\", \"https://(.*).us-(west|east).host.bsky.network\")",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}