{
 "title": "Bsky indexer",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "rate_interval",
    "label": "Rate interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,2d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (instance) (irate(node_cpu_seconds_total{instance=\"host.docker.internal:9100\",job=\"node\",mode!=\"idle\"}[$__rate_interval]))/ sum by (instance) ((irate(node_cpu_seconds_total{instance=\"host.docker.internal:9100\",job=\"node\"}[$__rate_interval]))))*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((avg_over_time(node_memory_MemAvailable_bytes{instance=\"host.docker.internal:9100\",job=\"node\"}[$__rate_interval]) * 100) / avg_over_time(node_memory_MemTotal_bytes{instance=\"host.docker.internal:9100\",job=\"node\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (node_filesystem_size_bytes{mountpoint='/4t'}-node_filesystem_free_bytes{mountpoint='/4t'})/(node_filesystem_size_bytes{mountpoint='/4t'})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total accs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "repos_seen{job=\"db\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time to 6mil",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(6000000-repos_fully_indexed{job=\"db\"})/deriv(repos_fully_indexed{job=\"db\"}[1d])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time to 1TB",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "-1*1024*1024*1024*1024/deriv(node_filesystem_free_bytes{mountpoint='/4t'}[1d])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time to Full",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "-4*1024*1024*1024*1024/deriv(node_filesystem_free_bytes{mountpoint='/4t'}[1d])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IO write",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(node_disk_written_bytes_total{device=\"sda\"}[$rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk health",
   "type": "bargauge",
   "description": "Operating temperature: 0 to 70C\n\nWarranty: 3 years",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartmon_power_on_hours_raw_value{disk=\"/dev/sda\"}",
     "legendFormat": "power on"
    },
    {
     "expr": "smartmon_airflow_temperature_cel_raw_value{disk=\"/dev/sda\"}",
     "legendFormat": "disk temperature"
    },
    {
     "expr": "smartmon_erase_fail_count_total_raw_value{disk=\"/dev/sda\"}",
     "legendFormat": "bad sectors"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=\"host.docker.internal:9100\", job=\"node\"}[$rate_interval]) * 8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=\"host.docker.internal:9100\", job=\"node\"}[$rate_interval]) * 8",
     "legendFormat": "trans {{device}}"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{mountpoint='/4t'}-node_filesystem_free_bytes{mountpoint='/4t'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Indexed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "repos_fully_indexed{job=\"db\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Left to index",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "repos_seen - on(instance) (repos_failed + on(instance) repos_fully_indexed)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Indexing speed",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 11, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "repo/h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "deriv(repos_fully_indexed{job=\"db\"}[$rate_interval])*60*60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IO wait",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 14, "y": 4 },
   "targets": [
    {
     "expr": "(sum by(instance) (rate(node_cpu_seconds_total{instance=\"host.docker.internal:9100\",job=\"node\", mode=\"iowait\"}[$rate_interval])) / on(instance) group_left sum by (instance)((rate(node_cpu_seconds_total{instance=\"host.docker.internal:9100\",job=\"node\"}[$rate_interval]))))*100",
     "legendFormat": "Busy Iowait"
    }
   ]
  },
  {
   "title": "IO wear",
   "type": "gauge",
   "description": "1.315068 TBW/d is max for an SSD to survive 3 years.",
   "gridPos": { "h": 5, "w": 3, "x": 17, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "TBW/d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(rate(smartmon_total_lbas_written_raw_value{instance=\"host.docker.internal:9100\", disk=\"/dev/sda\"}[7d]) * 512 * 60 * 60 * 24)/(1024*1024*1024*1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time to Death",
   "type": "bargauge",
   "description": "Warranty: 1440 TBW or 3 years",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1440 / ((rate(smartmon_total_lbas_written_raw_value{instance=\"host.docker.internal:9100\", disk=\"/dev/sda\"}[7d]) * 512 * 60 * 60)/(1024*1024*1024*1024))",
     "legendFormat": "time left (at current wear rate)"
    },
    {
     "expr": "smartmon_total_lbas_written_raw_value{instance=\"host.docker.internal:9100\", disk=\"/dev/sda\"} * 512 / (1024 * 1024 * 1024 * 1024)",
     "legendFormat": "data written (out of 1440 TBW)"
    }
   ]
  },
  {
   "title": "Firehose",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "commits/s" } },
   "targets": [
    {
     "expr": "label_replace(sum by(remote) (rate(repo_commits_received_counter{remote=~\"https://amanita.us-east.host.bsky.network|https://enoki.us-east.host.bsky.network|https://inkcap.us-east.host.bsky.network|https://lionsmane.us-east.host.bsky.network|https://morel.us-east.host.bsky.network|https://oyster.us-east.host.bsky.network|https://porcini.us-east.host.bsky.network|https://puffball.us-east.host.bsky.network|https://shiitake.us-east.host.bsky.network|https://shimeji.us-east.host.bsky.network\"}[$rate_interval])), \"remote\", \"$1\", \"remote\", \"https://(.*).us-(west|east).host.bsky.network\")",
     "legendFormat": "{{remote}}"
    },
    {
     "expr": "label_replace(sum by(remote) (rate(repo_commits_received_counter{remote=~\"https://agaric.us-west.host.bsky.network|https://blewit.us-west.host.bsky.network|https://boletus.us-west.host.bsky.network|https://chaga.us-west.host.bsky.network|https://conocybe.us-west.host.bsky.network|https://hydnum.us-west.host.bsky.network|https://lepista.us-west.host.bsky.network|https://maitake.us-west.host.bsky.network|https://russula.us-west.host.bsky.network|https://verpa.us-west.host.bsky.network\"}[$rate_interval])), \"remote\", \"$1\", \"remote\", \"https://(.*).us-(west|east).host.bsky.network\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Delay-Catchup",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "label_replace(time() - repo_commit_received_timestamp, \"remote\", \"delay-$1\", \"remote\", \"https://(.*).us-(west|east).host.bsky.network\")",
     "legendFormat": "{{remote}}"
    },
    {
     "expr": "label_replace(deriv(repo_commit_received_timestamp[$rate_interval]), \"remote\", \"catchup-$1\", \"remote\", \"https://(.*).us-(west|east).host.bsky.network\")",
     "legendFormat": "{{remote}}"
    }
   ]
  },
  {
   "title": "Posts by language",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "posts/h" } },
   "targets": [
    {
     "expr": "sum by(lang) (rate(indexer_posts_by_language_count[$rate_interval])*60*60)",
     "legendFormat": "{{lang}}"
    }
   ]
  },
  {
   "title": "Repo fetch rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "repos/h" } },
   "targets": [
    {
     "expr": "label_replace(sum by(remote, success) (rate(indexer_repos_fetched_count{success=\"true\", remote=~\"https://amanita.us-east.host.bsky.network|https://enoki.us-east.host.bsky.network|https://inkcap.us-east.host.bsky.network|https://lionsmane.us-east.host.bsky.network|https://oyster.us-east.host.bsky.network|https://morel.us-east.host.bsky.network|https://porcini.us-east.host.bsky.network|https://puffball.us-east.host.bsky.network|https://shiitake.us-east.host.bsky.network\"}[$rate_interval])), \"remote\", \"$1\", \"remote\", \"https://(.*).us-(west|east).host.bsky.network\") * 60 * 60",
     "legendFormat": "{{remote}}"
    },
    {
     "expr": "label_replace(sum by(remote, success) (rate(indexer_repos_fetched_count{success=~\"true\", remote!~\"https://amanita.us-east.host.bsky.network|https://enoki.us-east.host.bsky.network|https://inkcap.us-east.host.bsky.network|https://lionsmane.us-east.host.bsky.network|https://oyster.us-east.host.bsky.network|https://morel.us-east.host.bsky.network|https://porcini.us-east.host.bsky.network|https://puffball.us-east.host.bsky.network|https://shiitake.us-east.host.bsky.network\"}[$rate_interval])), \"remote\", \"$1\", \"remote\", \"https://(.*).us-(west|east).host.bsky.network\") * 60 * 60",
     "legendFormat": "{{remote}}"
    },
    {
     "expr": "sum(rate(indexer_repos_fetched_count{success=\"false\"}[$rate_interval]))",
     "legendFormat": "failures"
    }
   ]
  },
  {
   "title": "Indexing queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum by(state) (indexer_queue_length)",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "sum by(success) (rate(indexer_repos_indexed_count[$rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Record indexing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "records/s" } },
   "targets": [
    {
     "expr": "sum(rate(indexer_records_inserted_count[$rate_interval]))",
     "legendFormat": "Inserted"
    },
    {
     "expr": "sum(rate(indexer_records_fetched_count[$rate_interval]))",
     "legendFormat": "Fetched"
    }
   ]
  }
 ]
}