{
 "title": "Bluesky indexer",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "rate_interval", "label": "Rate interval", "query": "1m,5m,10m,30m,1h,6h,12h,1d" },
   { "name": "disk_usage_window", "query": "1h,6h,12h,1d,7d,14d,30d" },
   { "name": "ssd_wear_window", "query": "6h,12h,1d,7d,14d,30d" },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(node_exporter_build_info,instance)"
    }
   },
   {
    "name": "storage_device",
    "label": "Storage device",
    "query": {
     "query": "label_values(smartmon_device_info{instance=\"$node\"},disk)"
    }
   },
   {
    "name": "storage_mountpoint",
    "label": "Storage mountpoint",
    "query": {
     "query": "label_values(node_filesystem_avail_bytes{instance=\"$node\"},mountpoint)"
    }
   },
   {
    "name": "network_iface",
    "label": "Network interface",
    "query": {
     "query": "label_values(node_network_speed_bytes{instance=\"$node\"},device)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Left to index",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "repos_seen - on(instance) (repos_failed + on(instance) repos_fully_indexed)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Largest 1st-party firehose delay",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - label_replace(repo_commit_received_timestamp{job=\"consumer\",remote=~\"https://.*\\\\.bsky\\\\.(network|social)\"}, \"remote\", \"$1\", \"remote\", \"https://((?U).*)(\\\\.host\\\\.bsky\\\\.network)?\")",
     "legendFormat": "{{remote}}"
    }
   ]
  },
  {
   "title": "$disk_usage_window disk space fill rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "-deriv(node_filesystem_free_bytes{instance=\"$node\",mountpoint=\"$storage_mountpoint\"}[$disk_usage_window]) * on () sum_over_time(absent_over_time(foo[1m])[$disk_usage_window:1s])",
     "legendFormat": " "
    },
    {
     "expr": "node_filesystem_free_bytes{instance=\"$node\",mountpoint=\"$storage_mountpoint\"} / clamp_min(-deriv(node_filesystem_free_bytes{instance=\"$node\",mountpoint=\"$storage_mountpoint\"}[$disk_usage_window]), 0.0001)",
     "legendFormat": "Time to full"
    }
   ]
  },
  {
   "title": "SSD endurance",
   "type": "stat",
   "description": "1 minus ratio of blocks written to specified endurance",
   "gridPos": { "h": 5, "w": 4, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - smartmon_total_lbas_written_raw_value{instance=\"$node\",disk=\"$storage_device\"} * 512 / (700 * 1024 * 1024 * 1024 * 1024)",
     "legendFormat": " "
    },
    {
     "expr": "(700 * 1024 * 1024 * 1024 * 1024 - (smartmon_total_lbas_written_raw_value{instance=\"$node\",disk=\"$storage_device\"}*512)) / (deriv(smartmon_total_lbas_written_raw_value{instance=\"$node\",disk=\"$storage_device\"}[$ssd_wear_window]) * 512)",
     "legendFormat": "Time to death (based on $ssd_wear_window usage)"
    }
   ]
  },
  { "title": "Repo counts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Repo counts",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "sum(repos_failed)", "legendFormat": "Failed" },
    { "expr": "sum(repos_fully_indexed)", "legendFormat": "Indexed" },
    { "expr": "sum(repos_seen)", "legendFormat": "Discovered" }
   ]
  },
  {
   "title": "Repo discovery rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "label_replace(sum by(job, remote) (rate(repo_discovered_counter[$rate_interval])), \"remote\", \"$1\", \"remote\", \"https://((?U).*)(\\\\.host\\\\.bsky\\\\.network)?\")",
     "legendFormat": "{{remote}}"
    }
   ]
  },
  { "title": "Indexing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Workers",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "sum(indexer_workers_count)", "legendFormat": "Indexer workers" },
    {
     "expr": "sum by(instance) (rate(node_cpu_seconds_total{job=\"node\", instance=\"$node\",mode=~\"system|user\"}[$rate_interval])) / on(instance) group_left sum by (instance)((rate(node_cpu_seconds_total{job=\"node\", instance=\"$node\"}[$rate_interval])))",
     "legendFormat": "CPU usage"
    },
    {
     "expr": "sum by(instance) (rate(node_cpu_seconds_total{job=\"node\", instance=\"$node\",mode=~\"iowait\"}[$rate_interval])) / on(instance) group_left sum by (instance)((rate(node_cpu_seconds_total{job=\"node\", instance=\"$node\"}[$rate_interval])))",
     "legendFormat": "iowait"
    }
   ]
  },
  {
   "title": "Record indexing",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "records/s" } },
   "targets": [
    {
     "expr": "sum(rate(indexer_records_fetched_count[$rate_interval]))",
     "legendFormat": "Fetch rate"
    },
    {
     "expr": "sum(rate(indexer_records_inserted_count[$rate_interval]))",
     "legendFormat": "Insert rate"
    }
   ]
  },
  {
   "title": "Repo fetch rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "label_replace(sum by(remote) (rate(indexer_repos_fetched_count{success=\"true\"}[$rate_interval])), \"remote\", \"$1\", \"remote\", \"https://((?U).*)(\\\\.host\\\\.bsky\\\\.network)?\")",
     "legendFormat": "{{remote}}"
    },
    {
     "expr": "sum(rate(indexer_repos_fetched_count{success=\"false\"}[$rate_interval]))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Indexing queue",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "sum by(state) (indexer_queue_length)",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "sum by(success) (rate(indexer_repos_indexed_count[$rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "1st party firehose", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Lag",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - label_replace(repo_commit_received_timestamp{job=\"consumer\", remote=~\"https://.*\\\\.bsky\\\\.(network|social)\"}, \"remote\", \"$1\", \"remote\", \"https://((?U).*)(\\\\.host\\\\.bsky\\\\.network)?\")",
     "legendFormat": "{{remote}}"
    }
   ]
  },
  {
   "title": "Firehose event rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "label_replace(sum by(remote) (rate(repo_commits_received_counter{remote=~\"https://.*\\\\.bsky\\\\.(network|social)\"}[$rate_interval])), \"remote\", \"$1\", \"remote\", \"https://((?U).*)(\\\\.host\\\\.bsky\\\\.network)?\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Advancing rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "label_replace(deriv(repo_commit_received_timestamp{job=\"consumer\",remote=~\"https://.*\\\\.bsky\\\\.(network|social)\"}[$rate_interval]), \"remote\", \"$1\", \"remote\", \"https://((?U).*)(\\\\\\\\.host\\\\\\\\.bsky\\\\\\\\.network)?\")",
     "legendFormat": "{{remote}}"
    }
   ]
  },
  {
   "title": "Firehose event rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "expr": "label_replace(sum by(type) (rate(repo_commits_received_counter{type!=\"#commit\",remote=~\"https://.*\\\\.bsky\\\\.(network|social)\"}[$rate_interval])), \"remote\", \"$1\", \"remote\", \"https://([^.]+)\\\\..*\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(sum by(type) (rate(repo_commits_received_counter{type=\"#commit\",remote=~\"https://.*\\\\.bsky\\\\.(network|social)\"}[$rate_interval])), \"remote\", \"$1\", \"remote\", \"https://([^.]+)\\\\..*\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bad record counts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "label_replace(sum by(pds) (consumer_bad_records{pds=~\"https://.*\\\\.bsky\\\\.(network|social)\"}), \"pds\", \"$1\", \"pds\", \"https://((?U).*)(\\\\.host\\\\.bsky\\\\.network)?\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bad records",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "targets": [
    {
     "expr": "consumer_bad_records{pds=~\"https://.*\\\\.bsky\\\\.(network|social)\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Firehose connection errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 61 },
   "targets": [
    {
     "expr": "label_replace(sum by(remote) (rate(consumer_connection_failures{remote=~\"https://.*\\\\.bsky\\\\.(network|social)\"}[$rate_interval])), \"remote\", \"$1\", \"remote\", \"https://((?U).*)(\\\\.host\\\\.bsky\\\\.network)?\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "3rd party firehose",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 },
   "collapsed": true,
   "panels": [
    {
     "title": "Lag",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "time() - label_replace(repo_commit_received_timestamp{job=\"consumer\", remote!~\"https://.*\\\\.bsky\\\\.(network|social)\"}, \"remote\", \"$1\", \"remote\", \"https://((?U).*)(\\\\.host\\\\.bsky\\\\.network)?\")",
       "legendFormat": "{{remote}}"
      }
     ]
    },
    {
     "title": "Firehose event rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "label_replace(sum by(remote) (rate(repo_commits_received_counter{remote!~\"https://.*\\\\.bsky\\\\.(network|social)\"}[$rate_interval])), \"remote\", \"$1\", \"remote\", \"https://((?U).*)(\\\\.host\\\\.bsky\\\\.network)?\")",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Advancing rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "label_replace(deriv(repo_commit_received_timestamp{job=\"consumer\",remote!~\"https://.*\\\\.bsky\\\\.(network|social)\"}[$rate_interval]), \"remote\", \"$1\", \"remote\", \"https://((?U).*)(\\\\\\\\.host\\\\\\\\.bsky\\\\\\\\.network)?\")",
       "legendFormat": "{{remote}}"
      }
     ]
    },
    {
     "title": "Firehose event rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
     "targets": [
      {
       "expr": "label_replace(sum by(type) (rate(repo_commits_received_counter{type!=\"#commit\",remote!~\"https://.*\\\\.bsky\\\\.(network|social)\"}[$rate_interval])), \"remote\", \"$1\", \"remote\", \"https://([^.]+)\\\\..*\")",
       "legendFormat": "__auto"
      },
      {
       "expr": "label_replace(sum by(type) (rate(repo_commits_received_counter{type=\"#commit\",remote!~\"https://.*\\\\.bsky\\\\.(network|social)\"}[$rate_interval])), \"remote\", \"$1\", \"remote\", \"https://([^.]+)\\\\..*\")",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Bad record counts",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "targets": [
      {
       "expr": "label_replace(sum by(pds) (consumer_bad_records{pds!~\"https://.*\\\\.bsky\\\\.(network|social)\"}), \"pds\", \"$1\", \"pds\", \"https://((?U).*)(\\\\.host\\\\.bsky\\\\.network)?\")",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Bad records",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "targets": [
      {
       "expr": "consumer_bad_records{pds!~\"https://.*\\\\.bsky\\\\.(network|social)\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Firehose connection errors",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "label_replace(sum by(remote) (rate(consumer_connection_failures{remote!~\"https://.*\\\\.bsky\\\\.(network|social)\"}[$rate_interval])), \"remote\", \"$1\", \"remote\", \"https://((?U).*)(\\\\.host\\\\.bsky\\\\.network)?\")",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "Disk space",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"$node\", mountpoint=\"$storage_mountpoint\"}",
     "legendFormat": "Size: {{mountpoint}}"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=\"$node\", mountpoint=\"$storage_mountpoint\"} - on(mountpoint,instance) node_filesystem_free_bytes{instance=\"$node\", mountpoint=\"$storage_mountpoint\"}",
     "legendFormat": "Used: {{mountpoint}}"
    },
    {
     "expr": "deriv(node_filesystem_free_bytes{mountpoint=\"$storage_mountpoint\"}[$rate_interval]) * -1",
     "legendFormat": "Fill rate: {{mountpoint}}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=\"$node\", job=\"node\", device=\"$network_iface\"}[$rate_interval]) * 8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=\"$node\", job=\"node\", device=\"$network_iface\"}[$rate_interval]) * 8",
     "legendFormat": "trans {{device}} "
    }
   ]
  }
 ]
}